/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

(function () {
  "use strict";

  var overlays = new Map();
  var scanPending = false;
  var trackingFrame = null;
  var ASCIINEMA_URL =
    /^https?:\/\/(?:www\.)?asciinema\.org\/a\/([A-Za-z0-9_-]+)(?:[/?#].*)?$/i;

  function linkUrl(element) {
    var href =
      element.getAttribute("href") ||
      element.getAttribute("xlink:href") ||
      (element.href && element.href.baseVal) ||
      "";

    try {
      return new URL(href, document.baseURI).href;
    } catch (_error) {
      return href;
    }
  }

  function linkBounds(element) {
    var rect = element.getBoundingClientRect();
    if (rect.width > 1 && rect.height > 1) {
      return rect;
    }

    // Some SVG <a> elements report an empty client rect. Transform their SVG
    // bounding box into viewport coordinates as a fallback.
    try {
      var box = element.getBBox();
      var matrix = element.getScreenCTM();
      if (!matrix) {
        return rect;
      }

      var points = [
        new DOMPoint(box.x, box.y).matrixTransform(matrix),
        new DOMPoint(box.x + box.width, box.y).matrixTransform(matrix),
        new DOMPoint(box.x, box.y + box.height).matrixTransform(matrix),
        new DOMPoint(box.x + box.width, box.y + box.height).matrixTransform(
          matrix
        ),
      ];
      var xs = points.map(function (point) {
        return point.x;
      });
      var ys = points.map(function (point) {
        return point.y;
      });
      var left = Math.min.apply(Math, xs);
      var top = Math.min.apply(Math, ys);

      return {
        left: left,
        top: top,
        right: Math.max.apply(Math, xs),
        bottom: Math.max.apply(Math, ys),
        width: Math.max.apply(Math, xs) - left,
        height: Math.max.apply(Math, ys) - top,
      };
    } catch (_error) {
      return rect;
    }
  }

  function positionOverlay(element, overlay) {
    var rect = linkBounds(element);
    var visible =
      element.isConnected &&
      rect.width > 1 &&
      rect.height > 1 &&
      rect.right > 0 &&
      rect.bottom > 0 &&
      rect.left < window.innerWidth &&
      rect.top < window.innerHeight;

    overlay.hidden = !visible;
    if (!visible) {
      return;
    }

    overlay.style.left = rect.left + "px";
    overlay.style.top = rect.top + "px";
    overlay.style.width = rect.width + "px";
    overlay.style.height = rect.height + "px";
  }

  function trackOverlays() {
    trackingFrame = null;

    overlays.forEach(function (overlay, element) {
      if (!element.isConnected) {
        overlay.remove();
        overlays.delete(element);
        return;
      }
      positionOverlay(element, overlay);
    });

    if (overlays.size) {
      trackingFrame = requestAnimationFrame(trackOverlays);
    }
  }

  function startTracking() {
    if (trackingFrame === null) {
      trackingFrame = requestAnimationFrame(trackOverlays);
    }
  }

  function addOverlay(element, asciinemaId) {
    var overlay = document.createElement("div");
    overlay.className = "asciinema-element";
    overlay.style.position = "fixed";
    overlay.style.zIndex = "10";
    overlay.style.background = "#000";
    overlay.style.boxSizing = "border-box";
    overlay.style.overflow = "hidden";

    var iframe = document.createElement("iframe");
    // This is the iframe URL generated by asciinema.org's documented
    // recording-specific /a/{id}.js embed widget.
    iframe.src = "https://asciinema.org/a/" + asciinemaId + "/iframe";
    iframe.title = "Asciinema recording " + asciinemaId;
    iframe.allow = "fullscreen";
    iframe.style.display = "block";
    iframe.style.width = "100%";
    iframe.style.height = "100%";
    iframe.style.border = "0";

    overlay.appendChild(iframe);
    document.body.appendChild(overlay);
    overlays.set(element, overlay);
    positionOverlay(element, overlay);
    startTracking();
  }

  function scan() {
    scanPending = false;

    // Slides has changed its page-container classes over time. The linked
    // objects in presentation/preview mode are still SVG anchors, so scan the
    // rendered SVG rather than depending on a private Google class name.
    document.querySelectorAll("svg a").forEach(function (element) {
      if (overlays.has(element)) {
        return;
      }

      var match = linkUrl(element).match(ASCIINEMA_URL);
      if (match) {
        addOverlay(element, match[1]);
      }
    });
  }

  function scheduleScan() {
    if (!scanPending) {
      scanPending = true;
      requestAnimationFrame(scan);
    }
  }

  function setupListener() {
    scan();
    new MutationObserver(scheduleScan).observe(document.documentElement, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["href", "xlink:href"],
    });
  }

  setupListener();
})();
